export const REQUEST_SIMULATION = "REQUEST_SIMULATION";
export const RECEIVE_SIMULATION = "RECEIVE_SIMULATION";
export const RECEIVE_ERROR = "RECEIVE_ERROR";

export const SELECT_AMOUNT = "SELECT_AMOUNT";
export const SELECT_CURRENCY_PAIR = "SELECT_CURRENCY_PAIR";
export const SELECT_STRATEGY = "SELECT_STRATEGY";
export const SELECT_START_DATE = "SELECT_START_DATE";
export const SELECT_END_DATE = "SELECT_END_DATE";
