export const REQUEST_SIMULATION = "REQUEST_SIMULATION";
export const RECEIVE_SIMULATION = "RECEIVE_SIMULATION";
export const RECEIVE_ERROR = "RECEIVE_ERROR";

export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const SELECT_CURRENCY_PAIR = "SELECT_CURRENCY_PAIR";
export const SELECT_STRATEGY = "SELECT_STRATEGY";
export const SELECT_START_DATE = "SELECT_START_DATE";
export const SELECT_END_DATE = "SELECT_END_DATE";
export const CHANGE_FAST_PERIOD = "CHANGE_FAST_PERIOD";
export const CHANGE_SLOW_PERIOD = "CHANGE_SLOW_PERIOD";
export const CHANGE_SIGNAL_PERIOD = "CHANGE_SIGNAL_PERIOD";
export const SELECT_SIMPLE_MA_OSCILLATOR = "SELECT_SIMPLE_MA_OSCILLATOR";
export const SELECT_SIMPLE_MA_SIGNAL = "SELECT_SIMPLE_MA_SIGNAL";
